function load_defx_keymap() 
  vim.api.nvim_buf_set_keymap(0, "n", "<CR>", "defx#do_action('open')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "l", "defx#do_action('open')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "h", "defx#do_action('cd', ['..'])", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "~", "defx#do_action('cd')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "c", "defx#do_action('copy')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "m", "defx#do_action('move')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "p", "defx#do_action('paste')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "o", "defx#do_action('open_tree', 'toggle')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "N", "defx#do_action('new_file')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "d", "defx#do_action('remove')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "r", "defx#do_action('rename')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "yy", "defx#do_action('yank_path')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "q", "defx#do_action('quit')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "cd", "defx#do_action('change_vim_cwd')", { noremap = true, silent = true, expr = true })
  vim.api.nvim_buf_set_keymap(0, "n", "<leader>j", "", { noremap = true, silent = true })
  vim.api.nvim_buf_set_keymap(0, "n", "<leader>k", "", { noremap = true, silent = true })
end

vim.cmd([[autocmd FileType defx call v:lua.load_defx_keymap()]])
vim.cmd([[autocmd FileType defx setlocal nonumber norelativenumber]])
vim.cmd([[autocmd BufLeave \[defx\]* call defx#call_action("add_session")]])
vim.cmd([[call defx#custom#column("git", "indicators", { "Modified": "GMO", "Staged": "GST", "Untracked": "GUT", "Renamed": "GRN", "Unmerged": "GUN", "Ignored": "GIG", "Deleted": "GDD", "Unknown": "GUK" })]])

vim.api.nvim_set_keymap("n", "<leader>o", ":Defx -session-file='/tmp/defx_session' -columns=space:space:indent:indent:space:icon:space:filename:type:git -show-ignored-files<CR>", { noremap = true, silent = true })
